// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: game/game.proto

package game

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CombatActionType int32

const (
	CombatActionType_NONE   CombatActionType = 0
	CombatActionType_ATTACK CombatActionType = 1
	CombatActionType_ULTI   CombatActionType = 2
	CombatActionType_SPELL  CombatActionType = 3
)

// Enum value maps for CombatActionType.
var (
	CombatActionType_name = map[int32]string{
		0: "NONE",
		1: "ATTACK",
		2: "ULTI",
		3: "SPELL",
	}
	CombatActionType_value = map[string]int32{
		"NONE":   0,
		"ATTACK": 1,
		"ULTI":   2,
		"SPELL":  3,
	}
)

func (x CombatActionType) Enum() *CombatActionType {
	p := new(CombatActionType)
	*p = x
	return p
}

func (x CombatActionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CombatActionType) Descriptor() protoreflect.EnumDescriptor {
	return file_game_game_proto_enumTypes[0].Descriptor()
}

func (CombatActionType) Type() protoreflect.EnumType {
	return &file_game_game_proto_enumTypes[0]
}

func (x CombatActionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CombatActionType.Descriptor instead.
func (CombatActionType) EnumDescriptor() ([]byte, []int) {
	return file_game_game_proto_rawDescGZIP(), []int{0}
}

type GameStateUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Players       []*PlayerState         `protobuf:"bytes,1,rep,name=players,proto3" json:"players,omitempty"`
	Tick          int32                  `protobuf:"varint,4,opt,name=tick,proto3" json:"tick,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameStateUpdate) Reset() {
	*x = GameStateUpdate{}
	mi := &file_game_game_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameStateUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameStateUpdate) ProtoMessage() {}

func (x *GameStateUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_game_game_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameStateUpdate.ProtoReflect.Descriptor instead.
func (*GameStateUpdate) Descriptor() ([]byte, []int) {
	return file_game_game_proto_rawDescGZIP(), []int{0}
}

func (x *GameStateUpdate) GetPlayers() []*PlayerState {
	if x != nil {
		return x.Players
	}
	return nil
}

func (x *GameStateUpdate) GetTick() int32 {
	if x != nil {
		return x.Tick
	}
	return 0
}

type PlayerState struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	PlayerId uint32                 `protobuf:"varint,1,opt,name=playerId,proto3" json:"playerId,omitempty"`
	X        float32                `protobuf:"fixed32,2,opt,name=x,proto3" json:"x,omitempty"`
	Y        float32                `protobuf:"fixed32,3,opt,name=y,proto3" json:"y,omitempty"`
	Z        float32                `protobuf:"fixed32,4,opt,name=z,proto3" json:"z,omitempty"`
	MoveX    float32                `protobuf:"fixed32,5,opt,name=moveX,proto3" json:"moveX,omitempty"`
	MoveY    float32                `protobuf:"fixed32,6,opt,name=moveY,proto3" json:"moveY,omitempty"`
	DirX     float32                `protobuf:"fixed32,7,opt,name=dirX,proto3" json:"dirX,omitempty"`
	DirY     float32                `protobuf:"fixed32,8,opt,name=dirY,proto3" json:"dirY,omitempty"`
	// Types that are valid to be assigned to CombatState:
	//
	//	*PlayerState_IsAttacking
	//	*PlayerState_IsUsingUlti
	//	*PlayerState_SpellId
	CombatState   isPlayerState_CombatState `protobuf_oneof:"combatState"`
	Tick          int32                     `protobuf:"varint,12,opt,name=tick,proto3" json:"tick,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerState) Reset() {
	*x = PlayerState{}
	mi := &file_game_game_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerState) ProtoMessage() {}

func (x *PlayerState) ProtoReflect() protoreflect.Message {
	mi := &file_game_game_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerState.ProtoReflect.Descriptor instead.
func (*PlayerState) Descriptor() ([]byte, []int) {
	return file_game_game_proto_rawDescGZIP(), []int{1}
}

func (x *PlayerState) GetPlayerId() uint32 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *PlayerState) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *PlayerState) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *PlayerState) GetZ() float32 {
	if x != nil {
		return x.Z
	}
	return 0
}

func (x *PlayerState) GetMoveX() float32 {
	if x != nil {
		return x.MoveX
	}
	return 0
}

func (x *PlayerState) GetMoveY() float32 {
	if x != nil {
		return x.MoveY
	}
	return 0
}

func (x *PlayerState) GetDirX() float32 {
	if x != nil {
		return x.DirX
	}
	return 0
}

func (x *PlayerState) GetDirY() float32 {
	if x != nil {
		return x.DirY
	}
	return 0
}

func (x *PlayerState) GetCombatState() isPlayerState_CombatState {
	if x != nil {
		return x.CombatState
	}
	return nil
}

func (x *PlayerState) GetIsAttacking() bool {
	if x != nil {
		if x, ok := x.CombatState.(*PlayerState_IsAttacking); ok {
			return x.IsAttacking
		}
	}
	return false
}

func (x *PlayerState) GetIsUsingUlti() bool {
	if x != nil {
		if x, ok := x.CombatState.(*PlayerState_IsUsingUlti); ok {
			return x.IsUsingUlti
		}
	}
	return false
}

func (x *PlayerState) GetSpellId() int32 {
	if x != nil {
		if x, ok := x.CombatState.(*PlayerState_SpellId); ok {
			return x.SpellId
		}
	}
	return 0
}

func (x *PlayerState) GetTick() int32 {
	if x != nil {
		return x.Tick
	}
	return 0
}

type isPlayerState_CombatState interface {
	isPlayerState_CombatState()
}

type PlayerState_IsAttacking struct {
	IsAttacking bool `protobuf:"varint,9,opt,name=isAttacking,proto3,oneof"`
}

type PlayerState_IsUsingUlti struct {
	IsUsingUlti bool `protobuf:"varint,10,opt,name=isUsingUlti,proto3,oneof"`
}

type PlayerState_SpellId struct {
	SpellId int32 `protobuf:"varint,11,opt,name=spellId,proto3,oneof"`
}

func (*PlayerState_IsAttacking) isPlayerState_CombatState() {}

func (*PlayerState_IsUsingUlti) isPlayerState_CombatState() {}

func (*PlayerState_SpellId) isPlayerState_CombatState() {}

var File_game_game_proto protoreflect.FileDescriptor

const file_game_game_proto_rawDesc = "" +
	"\n" +
	"\x0fgame/game.proto\x12\x04game\"R\n" +
	"\x0fGameStateUpdate\x12+\n" +
	"\aplayers\x18\x01 \x03(\v2\x11.game.PlayerStateR\aplayers\x12\x12\n" +
	"\x04tick\x18\x04 \x01(\x05R\x04tick\"\xae\x02\n" +
	"\vPlayerState\x12\x1a\n" +
	"\bplayerId\x18\x01 \x01(\rR\bplayerId\x12\f\n" +
	"\x01x\x18\x02 \x01(\x02R\x01x\x12\f\n" +
	"\x01y\x18\x03 \x01(\x02R\x01y\x12\f\n" +
	"\x01z\x18\x04 \x01(\x02R\x01z\x12\x14\n" +
	"\x05moveX\x18\x05 \x01(\x02R\x05moveX\x12\x14\n" +
	"\x05moveY\x18\x06 \x01(\x02R\x05moveY\x12\x12\n" +
	"\x04dirX\x18\a \x01(\x02R\x04dirX\x12\x12\n" +
	"\x04dirY\x18\b \x01(\x02R\x04dirY\x12\"\n" +
	"\visAttacking\x18\t \x01(\bH\x00R\visAttacking\x12\"\n" +
	"\visUsingUlti\x18\n" +
	" \x01(\bH\x00R\visUsingUlti\x12\x1a\n" +
	"\aspellId\x18\v \x01(\x05H\x00R\aspellId\x12\x12\n" +
	"\x04tick\x18\f \x01(\x05R\x04tickB\r\n" +
	"\vcombatState*=\n" +
	"\x10CombatActionType\x12\b\n" +
	"\x04NONE\x10\x00\x12\n" +
	"\n" +
	"\x06ATTACK\x10\x01\x12\b\n" +
	"\x04ULTI\x10\x02\x12\t\n" +
	"\x05SPELL\x10\x03B\x12Z\x10pkg/packets/gameb\x06proto3"

var (
	file_game_game_proto_rawDescOnce sync.Once
	file_game_game_proto_rawDescData []byte
)

func file_game_game_proto_rawDescGZIP() []byte {
	file_game_game_proto_rawDescOnce.Do(func() {
		file_game_game_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_game_game_proto_rawDesc), len(file_game_game_proto_rawDesc)))
	})
	return file_game_game_proto_rawDescData
}

var file_game_game_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_game_game_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_game_game_proto_goTypes = []any{
	(CombatActionType)(0),   // 0: game.CombatActionType
	(*GameStateUpdate)(nil), // 1: game.GameStateUpdate
	(*PlayerState)(nil),     // 2: game.PlayerState
}
var file_game_game_proto_depIdxs = []int32{
	2, // 0: game.GameStateUpdate.players:type_name -> game.PlayerState
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_game_game_proto_init() }
func file_game_game_proto_init() {
	if File_game_game_proto != nil {
		return
	}
	file_game_game_proto_msgTypes[1].OneofWrappers = []any{
		(*PlayerState_IsAttacking)(nil),
		(*PlayerState_IsUsingUlti)(nil),
		(*PlayerState_SpellId)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_game_game_proto_rawDesc), len(file_game_game_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_game_game_proto_goTypes,
		DependencyIndexes: file_game_game_proto_depIdxs,
		EnumInfos:         file_game_game_proto_enumTypes,
		MessageInfos:      file_game_game_proto_msgTypes,
	}.Build()
	File_game_game_proto = out.File
	file_game_game_proto_goTypes = nil
	file_game_game_proto_depIdxs = nil
}
