// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: match/match.proto

package match

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JoinMatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      uint32                 `protobuf:"varint,1,opt,name=playerId,proto3" json:"playerId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinMatchRequest) Reset() {
	*x = JoinMatchRequest{}
	mi := &file_match_match_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinMatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinMatchRequest) ProtoMessage() {}

func (x *JoinMatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_match_match_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinMatchRequest.ProtoReflect.Descriptor instead.
func (*JoinMatchRequest) Descriptor() ([]byte, []int) {
	return file_match_match_proto_rawDescGZIP(), []int{0}
}

func (x *JoinMatchRequest) GetPlayerId() uint32 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

var File_match_match_proto protoreflect.FileDescriptor

const file_match_match_proto_rawDesc = "" +
	"\n" +
	"\x11match/match.proto\x12\x05match\".\n" +
	"\x10JoinMatchRequest\x12\x1a\n" +
	"\bplayerId\x18\x01 \x01(\rR\bplayerIdB\x13Z\x11pkg/packets/matchb\x06proto3"

var (
	file_match_match_proto_rawDescOnce sync.Once
	file_match_match_proto_rawDescData []byte
)

func file_match_match_proto_rawDescGZIP() []byte {
	file_match_match_proto_rawDescOnce.Do(func() {
		file_match_match_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_match_match_proto_rawDesc), len(file_match_match_proto_rawDesc)))
	})
	return file_match_match_proto_rawDescData
}

var file_match_match_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_match_match_proto_goTypes = []any{
	(*JoinMatchRequest)(nil), // 0: match.JoinMatchRequest
}
var file_match_match_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_match_match_proto_init() }
func file_match_match_proto_init() {
	if File_match_match_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_match_match_proto_rawDesc), len(file_match_match_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_match_match_proto_goTypes,
		DependencyIndexes: file_match_match_proto_depIdxs,
		MessageInfos:      file_match_match_proto_msgTypes,
	}.Build()
	File_match_match_proto = out.File
	file_match_match_proto_goTypes = nil
	file_match_match_proto_depIdxs = nil
}
