// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: action/action.proto

package action

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PlayerAction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      uint32                 `protobuf:"varint,1,opt,name=playerId,proto3" json:"playerId,omitempty"`
	X             float32                `protobuf:"fixed32,2,opt,name=x,proto3" json:"x,omitempty"`
	Y             float32                `protobuf:"fixed32,3,opt,name=y,proto3" json:"y,omitempty"`
	Z             float32                `protobuf:"fixed32,4,opt,name=z,proto3" json:"z,omitempty"`
	MoveX         float32                `protobuf:"fixed32,5,opt,name=moveX,proto3" json:"moveX,omitempty"`
	MoveY         float32                `protobuf:"fixed32,6,opt,name=moveY,proto3" json:"moveY,omitempty"`
	DirX_Attack   float32                `protobuf:"fixed32,7,opt,name=dirX_Attack,json=dirXAttack,proto3" json:"dirX_Attack,omitempty"`
	DirY_Attack   float32                `protobuf:"fixed32,8,opt,name=dirY_Attack,json=dirYAttack,proto3" json:"dirY_Attack,omitempty"`
	Attack        bool                   `protobuf:"varint,9,opt,name=attack,proto3" json:"attack,omitempty"`
	Phaser        int32                  `protobuf:"varint,10,opt,name=phaser,proto3" json:"phaser,omitempty"`
	IsUlt         bool                   `protobuf:"varint,11,opt,name=isUlt,proto3" json:"isUlt,omitempty"`
	Tick          int32                  `protobuf:"varint,12,opt,name=tick,proto3" json:"tick,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerAction) Reset() {
	*x = PlayerAction{}
	mi := &file_action_action_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerAction) ProtoMessage() {}

func (x *PlayerAction) ProtoReflect() protoreflect.Message {
	mi := &file_action_action_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerAction.ProtoReflect.Descriptor instead.
func (*PlayerAction) Descriptor() ([]byte, []int) {
	return file_action_action_proto_rawDescGZIP(), []int{0}
}

func (x *PlayerAction) GetPlayerId() uint32 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *PlayerAction) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *PlayerAction) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *PlayerAction) GetZ() float32 {
	if x != nil {
		return x.Z
	}
	return 0
}

func (x *PlayerAction) GetMoveX() float32 {
	if x != nil {
		return x.MoveX
	}
	return 0
}

func (x *PlayerAction) GetMoveY() float32 {
	if x != nil {
		return x.MoveY
	}
	return 0
}

func (x *PlayerAction) GetDirX_Attack() float32 {
	if x != nil {
		return x.DirX_Attack
	}
	return 0
}

func (x *PlayerAction) GetDirY_Attack() float32 {
	if x != nil {
		return x.DirY_Attack
	}
	return 0
}

func (x *PlayerAction) GetAttack() bool {
	if x != nil {
		return x.Attack
	}
	return false
}

func (x *PlayerAction) GetPhaser() int32 {
	if x != nil {
		return x.Phaser
	}
	return 0
}

func (x *PlayerAction) GetIsUlt() bool {
	if x != nil {
		return x.IsUlt
	}
	return false
}

func (x *PlayerAction) GetTick() int32 {
	if x != nil {
		return x.Tick
	}
	return 0
}

var File_action_action_proto protoreflect.FileDescriptor

const file_action_action_proto_rawDesc = "" +
	"\n" +
	"\x13action/action.proto\x12\x06action\"\x9c\x02\n" +
	"\fPlayerAction\x12\x1a\n" +
	"\bplayerId\x18\x01 \x01(\rR\bplayerId\x12\f\n" +
	"\x01x\x18\x02 \x01(\x02R\x01x\x12\f\n" +
	"\x01y\x18\x03 \x01(\x02R\x01y\x12\f\n" +
	"\x01z\x18\x04 \x01(\x02R\x01z\x12\x14\n" +
	"\x05moveX\x18\x05 \x01(\x02R\x05moveX\x12\x14\n" +
	"\x05moveY\x18\x06 \x01(\x02R\x05moveY\x12\x1f\n" +
	"\vdirX_Attack\x18\a \x01(\x02R\n" +
	"dirXAttack\x12\x1f\n" +
	"\vdirY_Attack\x18\b \x01(\x02R\n" +
	"dirYAttack\x12\x16\n" +
	"\x06attack\x18\t \x01(\bR\x06attack\x12\x16\n" +
	"\x06phaser\x18\n" +
	" \x01(\x05R\x06phaser\x12\x14\n" +
	"\x05isUlt\x18\v \x01(\bR\x05isUlt\x12\x12\n" +
	"\x04tick\x18\f \x01(\x05R\x04tickB\x14Z\x12pkg/packets/actionb\x06proto3"

var (
	file_action_action_proto_rawDescOnce sync.Once
	file_action_action_proto_rawDescData []byte
)

func file_action_action_proto_rawDescGZIP() []byte {
	file_action_action_proto_rawDescOnce.Do(func() {
		file_action_action_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_action_action_proto_rawDesc), len(file_action_action_proto_rawDesc)))
	})
	return file_action_action_proto_rawDescData
}

var file_action_action_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_action_action_proto_goTypes = []any{
	(*PlayerAction)(nil), // 0: action.PlayerAction
}
var file_action_action_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_action_action_proto_init() }
func file_action_action_proto_init() {
	if File_action_action_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_action_action_proto_rawDesc), len(file_action_action_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_action_action_proto_goTypes,
		DependencyIndexes: file_action_action_proto_depIdxs,
		MessageInfos:      file_action_action_proto_msgTypes,
	}.Build()
	File_action_action_proto = out.File
	file_action_action_proto_goTypes = nil
	file_action_action_proto_depIdxs = nil
}
