server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: auth-service-auth
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**

        - id: auth-service-user
          uri: lb://auth-service
          predicates:
            - Path=/api/user/**
    loadbalancer:
      ribbon:
        enabled: false
app:
  security:
    public-endpoints:
      - /api/auth/**
      - /api/user/**
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://172.26.18.148:8761/eureka

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.netty.http.client: DEBUG
