server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enable: true
          lower-case-service-id: true
    loadbalancer:
      ribbon:
        enable: false
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/