apiVersion: v1
kind: Service
metadata:
  name: go-game-server-service
spec:
  selector:
    app: go-game-server
  ports:
    - name: udp
      protocol: UDP
      port: 8080
      targetPort: 8080
    - name: metrics
      protocol: TCP
      port: 2112
      targetPort: 2112
  type: NodePort  # hoặc LoadBalancer nếu trên cloud
