// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: meta_services.proto

package meta

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request để xác thực người chơi
type AuthenticateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthenticateRequest) Reset() {
	*x = AuthenticateRequest{}
	mi := &file_meta_services_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthenticateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticateRequest) ProtoMessage() {}

func (x *AuthenticateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_meta_services_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticateRequest.ProtoReflect.Descriptor instead.
func (*AuthenticateRequest) Descriptor() ([]byte, []int) {
	return file_meta_services_proto_rawDescGZIP(), []int{0}
}

func (x *AuthenticateRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *AuthenticateRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

// Response sau khi xác thực
type AuthenticateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SessionToken  string                 `protobuf:"bytes,3,opt,name=session_token,json=sessionToken,proto3" json:"session_token,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthenticateResponse) Reset() {
	*x = AuthenticateResponse{}
	mi := &file_meta_services_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthenticateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticateResponse) ProtoMessage() {}

func (x *AuthenticateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_meta_services_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticateResponse.ProtoReflect.Descriptor instead.
func (*AuthenticateResponse) Descriptor() ([]byte, []int) {
	return file_meta_services_proto_rawDescGZIP(), []int{1}
}

func (x *AuthenticateResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AuthenticateResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AuthenticateResponse) GetSessionToken() string {
	if x != nil {
		return x.SessionToken
	}
	return ""
}

func (x *AuthenticateResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Request để lấy thông tin hồ sơ người chơi
type GetPlayerProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlayerProfileRequest) Reset() {
	*x = GetPlayerProfileRequest{}
	mi := &file_meta_services_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlayerProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlayerProfileRequest) ProtoMessage() {}

func (x *GetPlayerProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_meta_services_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlayerProfileRequest.ProtoReflect.Descriptor instead.
func (*GetPlayerProfileRequest) Descriptor() ([]byte, []int) {
	return file_meta_services_proto_rawDescGZIP(), []int{2}
}

func (x *GetPlayerProfileRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// Thông tin hồ sơ người chơi
type PlayerProfile struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username       string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Level          int32                  `protobuf:"varint,3,opt,name=level,proto3" json:"level,omitempty"`
	Experience     int32                  `protobuf:"varint,4,opt,name=experience,proto3" json:"experience,omitempty"`
	Coins          int32                  `protobuf:"varint,5,opt,name=coins,proto3" json:"coins,omitempty"`
	InventoryItems []string               `protobuf:"bytes,6,rep,name=inventory_items,json=inventoryItems,proto3" json:"inventory_items,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PlayerProfile) Reset() {
	*x = PlayerProfile{}
	mi := &file_meta_services_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerProfile) ProtoMessage() {}

func (x *PlayerProfile) ProtoReflect() protoreflect.Message {
	mi := &file_meta_services_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerProfile.ProtoReflect.Descriptor instead.
func (*PlayerProfile) Descriptor() ([]byte, []int) {
	return file_meta_services_proto_rawDescGZIP(), []int{3}
}

func (x *PlayerProfile) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *PlayerProfile) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *PlayerProfile) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *PlayerProfile) GetExperience() int32 {
	if x != nil {
		return x.Experience
	}
	return 0
}

func (x *PlayerProfile) GetCoins() int32 {
	if x != nil {
		return x.Coins
	}
	return 0
}

func (x *PlayerProfile) GetInventoryItems() []string {
	if x != nil {
		return x.InventoryItems
	}
	return nil
}

// Response lấy thông tin hồ sơ
type GetPlayerProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Profile       *PlayerProfile         `protobuf:"bytes,2,opt,name=profile,proto3" json:"profile,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlayerProfileResponse) Reset() {
	*x = GetPlayerProfileResponse{}
	mi := &file_meta_services_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlayerProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlayerProfileResponse) ProtoMessage() {}

func (x *GetPlayerProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_meta_services_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlayerProfileResponse.ProtoReflect.Descriptor instead.
func (*GetPlayerProfileResponse) Descriptor() ([]byte, []int) {
	return file_meta_services_proto_rawDescGZIP(), []int{4}
}

func (x *GetPlayerProfileResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetPlayerProfileResponse) GetProfile() *PlayerProfile {
	if x != nil {
		return x.Profile
	}
	return nil
}

func (x *GetPlayerProfileResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Request để cập nhật kết quả trận đấu
type UpdateMatchResultRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	GainedExp     int32                  `protobuf:"varint,2,opt,name=gained_exp,json=gainedExp,proto3" json:"gained_exp,omitempty"`
	GainedCoins   int32                  `protobuf:"varint,3,opt,name=gained_coins,json=gainedCoins,proto3" json:"gained_coins,omitempty"`
	NewItems      []string               `protobuf:"bytes,4,rep,name=new_items,json=newItems,proto3" json:"new_items,omitempty"`
	WonMatch      bool                   `protobuf:"varint,5,opt,name=won_match,json=wonMatch,proto3" json:"won_match,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMatchResultRequest) Reset() {
	*x = UpdateMatchResultRequest{}
	mi := &file_meta_services_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMatchResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMatchResultRequest) ProtoMessage() {}

func (x *UpdateMatchResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_meta_services_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMatchResultRequest.ProtoReflect.Descriptor instead.
func (*UpdateMatchResultRequest) Descriptor() ([]byte, []int) {
	return file_meta_services_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateMatchResultRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateMatchResultRequest) GetGainedExp() int32 {
	if x != nil {
		return x.GainedExp
	}
	return 0
}

func (x *UpdateMatchResultRequest) GetGainedCoins() int32 {
	if x != nil {
		return x.GainedCoins
	}
	return 0
}

func (x *UpdateMatchResultRequest) GetNewItems() []string {
	if x != nil {
		return x.NewItems
	}
	return nil
}

func (x *UpdateMatchResultRequest) GetWonMatch() bool {
	if x != nil {
		return x.WonMatch
	}
	return false
}

// Response cập nhật kết quả trận đấu
type UpdateMatchResultResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Success        bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message        string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	UpdatedProfile *PlayerProfile         `protobuf:"bytes,3,opt,name=updated_profile,json=updatedProfile,proto3" json:"updated_profile,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateMatchResultResponse) Reset() {
	*x = UpdateMatchResultResponse{}
	mi := &file_meta_services_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMatchResultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMatchResultResponse) ProtoMessage() {}

func (x *UpdateMatchResultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_meta_services_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMatchResultResponse.ProtoReflect.Descriptor instead.
func (*UpdateMatchResultResponse) Descriptor() ([]byte, []int) {
	return file_meta_services_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateMatchResultResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateMatchResultResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UpdateMatchResultResponse) GetUpdatedProfile() *PlayerProfile {
	if x != nil {
		return x.UpdatedProfile
	}
	return nil
}

var File_meta_services_proto protoreflect.FileDescriptor

const file_meta_services_proto_rawDesc = "" +
	"\n" +
	"\x13meta_services.proto\x12\x04meta\"M\n" +
	"\x13AuthenticateRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"\x88\x01\n" +
	"\x14AuthenticateResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12#\n" +
	"\rsession_token\x18\x03 \x01(\tR\fsessionToken\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\"2\n" +
	"\x17GetPlayerProfileRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\xb9\x01\n" +
	"\rPlayerProfile\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x14\n" +
	"\x05level\x18\x03 \x01(\x05R\x05level\x12\x1e\n" +
	"\n" +
	"experience\x18\x04 \x01(\x05R\n" +
	"experience\x12\x14\n" +
	"\x05coins\x18\x05 \x01(\x05R\x05coins\x12'\n" +
	"\x0finventory_items\x18\x06 \x03(\tR\x0einventoryItems\"}\n" +
	"\x18GetPlayerProfileResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12-\n" +
	"\aprofile\x18\x02 \x01(\v2\x13.meta.PlayerProfileR\aprofile\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\xaf\x01\n" +
	"\x18UpdateMatchResultRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"gained_exp\x18\x02 \x01(\x05R\tgainedExp\x12!\n" +
	"\fgained_coins\x18\x03 \x01(\x05R\vgainedCoins\x12\x1b\n" +
	"\tnew_items\x18\x04 \x03(\tR\bnewItems\x12\x1b\n" +
	"\twon_match\x18\x05 \x01(\bR\bwonMatch\"\x8d\x01\n" +
	"\x19UpdateMatchResultResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12<\n" +
	"\x0fupdated_profile\x18\x03 \x01(\v2\x13.meta.PlayerProfileR\x0eupdatedProfile2T\n" +
	"\vAuthService\x12E\n" +
	"\fAuthenticate\x12\x19.meta.AuthenticateRequest\x1a\x1a.meta.AuthenticateResponse2\xb9\x01\n" +
	"\x0eProfileService\x12Q\n" +
	"\x10GetPlayerProfile\x12\x1d.meta.GetPlayerProfileRequest\x1a\x1e.meta.GetPlayerProfileResponse\x12T\n" +
	"\x11UpdateMatchResult\x12\x1e.meta.UpdateMatchResultRequest\x1a\x1f.meta.UpdateMatchResultResponseBa\n" +
	"\x13com.game.meta.protoP\x01ZHgithub.com/Vminhkiet/BattleGround-backend/go-game-server/pkg/protos/metab\x06proto3"

var (
	file_meta_services_proto_rawDescOnce sync.Once
	file_meta_services_proto_rawDescData []byte
)

func file_meta_services_proto_rawDescGZIP() []byte {
	file_meta_services_proto_rawDescOnce.Do(func() {
		file_meta_services_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_meta_services_proto_rawDesc), len(file_meta_services_proto_rawDesc)))
	})
	return file_meta_services_proto_rawDescData
}

var file_meta_services_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_meta_services_proto_goTypes = []any{
	(*AuthenticateRequest)(nil),       // 0: meta.AuthenticateRequest
	(*AuthenticateResponse)(nil),      // 1: meta.AuthenticateResponse
	(*GetPlayerProfileRequest)(nil),   // 2: meta.GetPlayerProfileRequest
	(*PlayerProfile)(nil),             // 3: meta.PlayerProfile
	(*GetPlayerProfileResponse)(nil),  // 4: meta.GetPlayerProfileResponse
	(*UpdateMatchResultRequest)(nil),  // 5: meta.UpdateMatchResultRequest
	(*UpdateMatchResultResponse)(nil), // 6: meta.UpdateMatchResultResponse
}
var file_meta_services_proto_depIdxs = []int32{
	3, // 0: meta.GetPlayerProfileResponse.profile:type_name -> meta.PlayerProfile
	3, // 1: meta.UpdateMatchResultResponse.updated_profile:type_name -> meta.PlayerProfile
	0, // 2: meta.AuthService.Authenticate:input_type -> meta.AuthenticateRequest
	2, // 3: meta.ProfileService.GetPlayerProfile:input_type -> meta.GetPlayerProfileRequest
	5, // 4: meta.ProfileService.UpdateMatchResult:input_type -> meta.UpdateMatchResultRequest
	1, // 5: meta.AuthService.Authenticate:output_type -> meta.AuthenticateResponse
	4, // 6: meta.ProfileService.GetPlayerProfile:output_type -> meta.GetPlayerProfileResponse
	6, // 7: meta.ProfileService.UpdateMatchResult:output_type -> meta.UpdateMatchResultResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_meta_services_proto_init() }
func file_meta_services_proto_init() {
	if File_meta_services_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_meta_services_proto_rawDesc), len(file_meta_services_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_meta_services_proto_goTypes,
		DependencyIndexes: file_meta_services_proto_depIdxs,
		MessageInfos:      file_meta_services_proto_msgTypes,
	}.Build()
	File_meta_services_proto = out.File
	file_meta_services_proto_goTypes = nil
	file_meta_services_proto_depIdxs = nil
}
