// common/proto/game_messages.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: game_messages.proto

package game

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Định nghĩa PlayerState là một enum trong Protobuf
type PlayerStateEnum int32

const (
	PlayerStateEnum_UNKNOWN   PlayerStateEnum = 0 // Luôn phải có giá trị 0 mặc định
	PlayerStateEnum_IDLE      PlayerStateEnum = 1
	PlayerStateEnum_MOVING    PlayerStateEnum = 2
	PlayerStateEnum_ATTACKING PlayerStateEnum = 3
	PlayerStateEnum_DEAD      PlayerStateEnum = 4
)

// Enum value maps for PlayerStateEnum.
var (
	PlayerStateEnum_name = map[int32]string{
		0: "UNKNOWN",
		1: "IDLE",
		2: "MOVING",
		3: "ATTACKING",
		4: "DEAD",
	}
	PlayerStateEnum_value = map[string]int32{
		"UNKNOWN":   0,
		"IDLE":      1,
		"MOVING":    2,
		"ATTACKING": 3,
		"DEAD":      4,
	}
)

func (x PlayerStateEnum) Enum() *PlayerStateEnum {
	p := new(PlayerStateEnum)
	*p = x
	return p
}

func (x PlayerStateEnum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PlayerStateEnum) Descriptor() protoreflect.EnumDescriptor {
	return file_game_messages_proto_enumTypes[0].Descriptor()
}

func (PlayerStateEnum) Type() protoreflect.EnumType {
	return &file_game_messages_proto_enumTypes[0]
}

func (x PlayerStateEnum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PlayerStateEnum.Descriptor instead.
func (PlayerStateEnum) EnumDescriptor() ([]byte, []int) {
	return file_game_messages_proto_rawDescGZIP(), []int{0}
}

// Thông điệp về vị trí và hướng của người chơi
type PlayerTransform struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	PosX          float32                `protobuf:"fixed32,2,opt,name=pos_x,json=posX,proto3" json:"pos_x,omitempty"`
	PosY          float32                `protobuf:"fixed32,3,opt,name=pos_y,json=posY,proto3" json:"pos_y,omitempty"`
	PosZ          float32                `protobuf:"fixed32,4,opt,name=pos_z,json=posZ,proto3" json:"pos_z,omitempty"`
	RotX          float32                `protobuf:"fixed32,5,opt,name=rot_x,json=rotX,proto3" json:"rot_x,omitempty"` // Quaternion components
	RotY          float32                `protobuf:"fixed32,6,opt,name=rot_y,json=rotY,proto3" json:"rot_y,omitempty"`
	RotZ          float32                `protobuf:"fixed32,7,opt,name=rot_z,json=rotZ,proto3" json:"rot_z,omitempty"`
	RotW          float32                `protobuf:"fixed32,8,opt,name=rot_w,json=rotW,proto3" json:"rot_w,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerTransform) Reset() {
	*x = PlayerTransform{}
	mi := &file_game_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerTransform) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerTransform) ProtoMessage() {}

func (x *PlayerTransform) ProtoReflect() protoreflect.Message {
	mi := &file_game_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerTransform.ProtoReflect.Descriptor instead.
func (*PlayerTransform) Descriptor() ([]byte, []int) {
	return file_game_messages_proto_rawDescGZIP(), []int{0}
}

func (x *PlayerTransform) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *PlayerTransform) GetPosX() float32 {
	if x != nil {
		return x.PosX
	}
	return 0
}

func (x *PlayerTransform) GetPosY() float32 {
	if x != nil {
		return x.PosY
	}
	return 0
}

func (x *PlayerTransform) GetPosZ() float32 {
	if x != nil {
		return x.PosZ
	}
	return 0
}

func (x *PlayerTransform) GetRotX() float32 {
	if x != nil {
		return x.RotX
	}
	return 0
}

func (x *PlayerTransform) GetRotY() float32 {
	if x != nil {
		return x.RotY
	}
	return 0
}

func (x *PlayerTransform) GetRotZ() float32 {
	if x != nil {
		return x.RotZ
	}
	return 0
}

func (x *PlayerTransform) GetRotW() float32 {
	if x != nil {
		return x.RotW
	}
	return 0
}

// Thông điệp đầu vào của người chơi
type PlayerInput struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PlayerId       string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	HorizontalAxis float32                `protobuf:"fixed32,2,opt,name=horizontal_axis,json=horizontalAxis,proto3" json:"horizontal_axis,omitempty"`
	VerticalAxis   float32                `protobuf:"fixed32,3,opt,name=vertical_axis,json=verticalAxis,proto3" json:"vertical_axis,omitempty"`
	JumpPressed    bool                   `protobuf:"varint,4,opt,name=jump_pressed,json=jumpPressed,proto3" json:"jump_pressed,omitempty"`
	ShootPressed   bool                   `protobuf:"varint,5,opt,name=shoot_pressed,json=shootPressed,proto3" json:"shoot_pressed,omitempty"` // Thêm các loại đầu vào khác
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PlayerInput) Reset() {
	*x = PlayerInput{}
	mi := &file_game_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerInput) ProtoMessage() {}

func (x *PlayerInput) ProtoReflect() protoreflect.Message {
	mi := &file_game_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerInput.ProtoReflect.Descriptor instead.
func (*PlayerInput) Descriptor() ([]byte, []int) {
	return file_game_messages_proto_rawDescGZIP(), []int{1}
}

func (x *PlayerInput) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *PlayerInput) GetHorizontalAxis() float32 {
	if x != nil {
		return x.HorizontalAxis
	}
	return 0
}

func (x *PlayerInput) GetVerticalAxis() float32 {
	if x != nil {
		return x.VerticalAxis
	}
	return 0
}

func (x *PlayerInput) GetJumpPressed() bool {
	if x != nil {
		return x.JumpPressed
	}
	return false
}

func (x *PlayerInput) GetShootPressed() bool {
	if x != nil {
		return x.ShootPressed
	}
	return false
}

// Thông điệp trạng thái game được gửi từ server đến client
type GameStateUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerTick    int64                  `protobuf:"varint,1,opt,name=server_tick,json=serverTick,proto3" json:"server_tick,omitempty"`
	PlayersStates []*PlayerState         `protobuf:"bytes,2,rep,name=players_states,json=playersStates,proto3" json:"players_states,omitempty"` // Thêm các trạng thái đối tượng khác trong game
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameStateUpdate) Reset() {
	*x = GameStateUpdate{}
	mi := &file_game_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameStateUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameStateUpdate) ProtoMessage() {}

func (x *GameStateUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_game_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameStateUpdate.ProtoReflect.Descriptor instead.
func (*GameStateUpdate) Descriptor() ([]byte, []int) {
	return file_game_messages_proto_rawDescGZIP(), []int{2}
}

func (x *GameStateUpdate) GetServerTick() int64 {
	if x != nil {
		return x.ServerTick
	}
	return 0
}

func (x *GameStateUpdate) GetPlayersStates() []*PlayerState {
	if x != nil {
		return x.PlayersStates
	}
	return nil
}

// Định nghĩa các loại thông điệp mà server có thể gửi (dạng Wrapper)
type ServerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ServerMessage_GameStateUpdate
	Payload       isServerMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerMessage) Reset() {
	*x = ServerMessage{}
	mi := &file_game_messages_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMessage) ProtoMessage() {}

func (x *ServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_game_messages_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMessage.ProtoReflect.Descriptor instead.
func (*ServerMessage) Descriptor() ([]byte, []int) {
	return file_game_messages_proto_rawDescGZIP(), []int{3}
}

func (x *ServerMessage) GetPayload() isServerMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ServerMessage) GetGameStateUpdate() *GameStateUpdate {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_GameStateUpdate); ok {
			return x.GameStateUpdate
		}
	}
	return nil
}

type isServerMessage_Payload interface {
	isServerMessage_Payload()
}

type ServerMessage_GameStateUpdate struct {
	GameStateUpdate *GameStateUpdate `protobuf:"bytes,1,opt,name=game_state_update,json=gameStateUpdate,proto3,oneof"` // Các loại thông điệp khác từ server
}

func (*ServerMessage_GameStateUpdate) isServerMessage_Payload() {}

type Vector2 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             float32                `protobuf:"fixed32,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             float32                `protobuf:"fixed32,2,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Vector2) Reset() {
	*x = Vector2{}
	mi := &file_game_messages_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vector2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vector2) ProtoMessage() {}

func (x *Vector2) ProtoReflect() protoreflect.Message {
	mi := &file_game_messages_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vector2.ProtoReflect.Descriptor instead.
func (*Vector2) Descriptor() ([]byte, []int) {
	return file_game_messages_proto_rawDescGZIP(), []int{4}
}

func (x *Vector2) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Vector2) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

// Thông điệp trạng thái đầy đủ của một người chơi (để gửi từ server)
type PlayerState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CharacterId   string                 `protobuf:"bytes,2,opt,name=character_id,json=characterId,proto3" json:"character_id,omitempty"`
	Position      *Vector2               `protobuf:"bytes,3,opt,name=position,proto3" json:"position,omitempty"`   // Sử dụng message Vector2 ở đây
	Direction     *Vector2               `protobuf:"bytes,4,opt,name=direction,proto3" json:"direction,omitempty"` // Sử dụng message Vector2 ở đây
	Health        float32                `protobuf:"fixed32,5,opt,name=health,proto3" json:"health,omitempty"`
	MaxHealth     float32                `protobuf:"fixed32,6,opt,name=max_health,json=maxHealth,proto3" json:"max_health,omitempty"`
	State         PlayerStateEnum        `protobuf:"varint,7,opt,name=state,proto3,enum=game.PlayerStateEnum" json:"state,omitempty"` // Sử dụng enum PlayerStateEnum ở đây
	LastInputTick int32                  `protobuf:"varint,8,opt,name=last_input_tick,json=lastInputTick,proto3" json:"last_input_tick,omitempty"`
	Score         int32                  `protobuf:"varint,9,opt,name=score,proto3" json:"score,omitempty"`
	Kills         int32                  `protobuf:"varint,10,opt,name=kills,proto3" json:"kills,omitempty"`
	Deaths        int32                  `protobuf:"varint,11,opt,name=deaths,proto3" json:"deaths,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerState) Reset() {
	*x = PlayerState{}
	mi := &file_game_messages_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerState) ProtoMessage() {}

func (x *PlayerState) ProtoReflect() protoreflect.Message {
	mi := &file_game_messages_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerState.ProtoReflect.Descriptor instead.
func (*PlayerState) Descriptor() ([]byte, []int) {
	return file_game_messages_proto_rawDescGZIP(), []int{5}
}

func (x *PlayerState) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *PlayerState) GetCharacterId() string {
	if x != nil {
		return x.CharacterId
	}
	return ""
}

func (x *PlayerState) GetPosition() *Vector2 {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *PlayerState) GetDirection() *Vector2 {
	if x != nil {
		return x.Direction
	}
	return nil
}

func (x *PlayerState) GetHealth() float32 {
	if x != nil {
		return x.Health
	}
	return 0
}

func (x *PlayerState) GetMaxHealth() float32 {
	if x != nil {
		return x.MaxHealth
	}
	return 0
}

func (x *PlayerState) GetState() PlayerStateEnum {
	if x != nil {
		return x.State
	}
	return PlayerStateEnum_UNKNOWN
}

func (x *PlayerState) GetLastInputTick() int32 {
	if x != nil {
		return x.LastInputTick
	}
	return 0
}

func (x *PlayerState) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *PlayerState) GetKills() int32 {
	if x != nil {
		return x.Kills
	}
	return 0
}

func (x *PlayerState) GetDeaths() int32 {
	if x != nil {
		return x.Deaths
	}
	return 0
}

// message GameStateUpdate {
// int64 server_tick = 1;
// repeated PlayerState players_states = 2; // Gửi toàn bộ trạng thái người chơi
// // Thêm các trạng thái đối tượng khác trong game
// }
type ClientMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ClientMessage_PlayerInput
	//	*ClientMessage_JoinRequest
	//	*ClientMessage_LeaveRequest
	Payload       isClientMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientMessage) Reset() {
	*x = ClientMessage{}
	mi := &file_game_messages_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientMessage) ProtoMessage() {}

func (x *ClientMessage) ProtoReflect() protoreflect.Message {
	mi := &file_game_messages_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientMessage.ProtoReflect.Descriptor instead.
func (*ClientMessage) Descriptor() ([]byte, []int) {
	return file_game_messages_proto_rawDescGZIP(), []int{6}
}

func (x *ClientMessage) GetPayload() isClientMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ClientMessage) GetPlayerInput() *PlayerInput {
	if x != nil {
		if x, ok := x.Payload.(*ClientMessage_PlayerInput); ok {
			return x.PlayerInput
		}
	}
	return nil
}

func (x *ClientMessage) GetJoinRequest() *JoinRequest {
	if x != nil {
		if x, ok := x.Payload.(*ClientMessage_JoinRequest); ok {
			return x.JoinRequest
		}
	}
	return nil
}

func (x *ClientMessage) GetLeaveRequest() *LeaveRequest {
	if x != nil {
		if x, ok := x.Payload.(*ClientMessage_LeaveRequest); ok {
			return x.LeaveRequest
		}
	}
	return nil
}

type isClientMessage_Payload interface {
	isClientMessage_Payload()
}

type ClientMessage_PlayerInput struct {
	PlayerInput *PlayerInput `protobuf:"bytes,1,opt,name=player_input,json=playerInput,proto3,oneof"`
}

type ClientMessage_JoinRequest struct {
	JoinRequest *JoinRequest `protobuf:"bytes,2,opt,name=join_request,json=joinRequest,proto3,oneof"` // Đảm bảo dòng này có
}

type ClientMessage_LeaveRequest struct {
	LeaveRequest *LeaveRequest `protobuf:"bytes,3,opt,name=leave_request,json=leaveRequest,proto3,oneof"` // Đảm bảo dòng này có
}

func (*ClientMessage_PlayerInput) isClientMessage_Payload() {}

func (*ClientMessage_JoinRequest) isClientMessage_Payload() {}

func (*ClientMessage_LeaveRequest) isClientMessage_Payload() {}

type JoinRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	CharacterId   string                 `protobuf:"bytes,3,opt,name=character_id,json=characterId,proto3" json:"character_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinRequest) Reset() {
	*x = JoinRequest{}
	mi := &file_game_messages_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRequest) ProtoMessage() {}

func (x *JoinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_messages_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRequest.ProtoReflect.Descriptor instead.
func (*JoinRequest) Descriptor() ([]byte, []int) {
	return file_game_messages_proto_rawDescGZIP(), []int{7}
}

func (x *JoinRequest) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *JoinRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *JoinRequest) GetCharacterId() string {
	if x != nil {
		return x.CharacterId
	}
	return ""
}

type LeaveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveRequest) Reset() {
	*x = LeaveRequest{}
	mi := &file_game_messages_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveRequest) ProtoMessage() {}

func (x *LeaveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_messages_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveRequest.ProtoReflect.Descriptor instead.
func (*LeaveRequest) Descriptor() ([]byte, []int) {
	return file_game_messages_proto_rawDescGZIP(), []int{8}
}

func (x *LeaveRequest) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *LeaveRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

var File_game_messages_proto protoreflect.FileDescriptor

const file_game_messages_proto_rawDesc = "" +
	"\n" +
	"\x13game_messages.proto\x12\x04game\"\xc1\x01\n" +
	"\x0fPlayerTransform\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12\x13\n" +
	"\x05pos_x\x18\x02 \x01(\x02R\x04posX\x12\x13\n" +
	"\x05pos_y\x18\x03 \x01(\x02R\x04posY\x12\x13\n" +
	"\x05pos_z\x18\x04 \x01(\x02R\x04posZ\x12\x13\n" +
	"\x05rot_x\x18\x05 \x01(\x02R\x04rotX\x12\x13\n" +
	"\x05rot_y\x18\x06 \x01(\x02R\x04rotY\x12\x13\n" +
	"\x05rot_z\x18\a \x01(\x02R\x04rotZ\x12\x13\n" +
	"\x05rot_w\x18\b \x01(\x02R\x04rotW\"\xc0\x01\n" +
	"\vPlayerInput\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12'\n" +
	"\x0fhorizontal_axis\x18\x02 \x01(\x02R\x0ehorizontalAxis\x12#\n" +
	"\rvertical_axis\x18\x03 \x01(\x02R\fverticalAxis\x12!\n" +
	"\fjump_pressed\x18\x04 \x01(\bR\vjumpPressed\x12#\n" +
	"\rshoot_pressed\x18\x05 \x01(\bR\fshootPressed\"l\n" +
	"\x0fGameStateUpdate\x12\x1f\n" +
	"\vserver_tick\x18\x01 \x01(\x03R\n" +
	"serverTick\x128\n" +
	"\x0eplayers_states\x18\x02 \x03(\v2\x11.game.PlayerStateR\rplayersStates\"_\n" +
	"\rServerMessage\x12C\n" +
	"\x11game_state_update\x18\x01 \x01(\v2\x15.game.GameStateUpdateH\x00R\x0fgameStateUpdateB\t\n" +
	"\apayload\"%\n" +
	"\aVector2\x12\f\n" +
	"\x01x\x18\x01 \x01(\x02R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x02R\x01y\"\xf1\x02\n" +
	"\vPlayerState\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12!\n" +
	"\fcharacter_id\x18\x02 \x01(\tR\vcharacterId\x12)\n" +
	"\bposition\x18\x03 \x01(\v2\r.game.Vector2R\bposition\x12+\n" +
	"\tdirection\x18\x04 \x01(\v2\r.game.Vector2R\tdirection\x12\x16\n" +
	"\x06health\x18\x05 \x01(\x02R\x06health\x12\x1d\n" +
	"\n" +
	"max_health\x18\x06 \x01(\x02R\tmaxHealth\x12+\n" +
	"\x05state\x18\a \x01(\x0e2\x15.game.PlayerStateEnumR\x05state\x12&\n" +
	"\x0flast_input_tick\x18\b \x01(\x05R\rlastInputTick\x12\x14\n" +
	"\x05score\x18\t \x01(\x05R\x05score\x12\x14\n" +
	"\x05kills\x18\n" +
	" \x01(\x05R\x05kills\x12\x16\n" +
	"\x06deaths\x18\v \x01(\x05R\x06deaths\"\xc5\x01\n" +
	"\rClientMessage\x126\n" +
	"\fplayer_input\x18\x01 \x01(\v2\x11.game.PlayerInputH\x00R\vplayerInput\x126\n" +
	"\fjoin_request\x18\x02 \x01(\v2\x11.game.JoinRequestH\x00R\vjoinRequest\x129\n" +
	"\rleave_request\x18\x03 \x01(\v2\x12.game.LeaveRequestH\x00R\fleaveRequestB\t\n" +
	"\apayload\"l\n" +
	"\vJoinRequest\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12!\n" +
	"\fcharacter_id\x18\x03 \x01(\tR\vcharacterId\"J\n" +
	"\fLeaveRequest\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId*M\n" +
	"\x0fPlayerStateEnum\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\b\n" +
	"\x04IDLE\x10\x01\x12\n" +
	"\n" +
	"\x06MOVING\x10\x02\x12\r\n" +
	"\tATTACKING\x10\x03\x12\b\n" +
	"\x04DEAD\x10\x04BWZHgithub.com/Vminhkiet/BattleGround-backend/go-game-server/pkg/protos/game\xaa\x02\n" +
	"Game.Protob\x06proto3"

var (
	file_game_messages_proto_rawDescOnce sync.Once
	file_game_messages_proto_rawDescData []byte
)

func file_game_messages_proto_rawDescGZIP() []byte {
	file_game_messages_proto_rawDescOnce.Do(func() {
		file_game_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_game_messages_proto_rawDesc), len(file_game_messages_proto_rawDesc)))
	})
	return file_game_messages_proto_rawDescData
}

var file_game_messages_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_game_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_game_messages_proto_goTypes = []any{
	(PlayerStateEnum)(0),    // 0: game.PlayerStateEnum
	(*PlayerTransform)(nil), // 1: game.PlayerTransform
	(*PlayerInput)(nil),     // 2: game.PlayerInput
	(*GameStateUpdate)(nil), // 3: game.GameStateUpdate
	(*ServerMessage)(nil),   // 4: game.ServerMessage
	(*Vector2)(nil),         // 5: game.Vector2
	(*PlayerState)(nil),     // 6: game.PlayerState
	(*ClientMessage)(nil),   // 7: game.ClientMessage
	(*JoinRequest)(nil),     // 8: game.JoinRequest
	(*LeaveRequest)(nil),    // 9: game.LeaveRequest
}
var file_game_messages_proto_depIdxs = []int32{
	6, // 0: game.GameStateUpdate.players_states:type_name -> game.PlayerState
	3, // 1: game.ServerMessage.game_state_update:type_name -> game.GameStateUpdate
	5, // 2: game.PlayerState.position:type_name -> game.Vector2
	5, // 3: game.PlayerState.direction:type_name -> game.Vector2
	0, // 4: game.PlayerState.state:type_name -> game.PlayerStateEnum
	2, // 5: game.ClientMessage.player_input:type_name -> game.PlayerInput
	8, // 6: game.ClientMessage.join_request:type_name -> game.JoinRequest
	9, // 7: game.ClientMessage.leave_request:type_name -> game.LeaveRequest
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_game_messages_proto_init() }
func file_game_messages_proto_init() {
	if File_game_messages_proto != nil {
		return
	}
	file_game_messages_proto_msgTypes[3].OneofWrappers = []any{
		(*ServerMessage_GameStateUpdate)(nil),
	}
	file_game_messages_proto_msgTypes[6].OneofWrappers = []any{
		(*ClientMessage_PlayerInput)(nil),
		(*ClientMessage_JoinRequest)(nil),
		(*ClientMessage_LeaveRequest)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_game_messages_proto_rawDesc), len(file_game_messages_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_game_messages_proto_goTypes,
		DependencyIndexes: file_game_messages_proto_depIdxs,
		EnumInfos:         file_game_messages_proto_enumTypes,
		MessageInfos:      file_game_messages_proto_msgTypes,
	}.Build()
	File_game_messages_proto = out.File
	file_game_messages_proto_goTypes = nil
	file_game_messages_proto_depIdxs = nil
}
